---
 - name: Provision EC2 Instance
   ec2:
     key_name: "{{ ec2_keypair }}"
     group_id: "{{ ec2_security_group }}"
     instance_type: "{{ ec2_instance_type }}"
     image: "{{ ec2_image }}"
     vpc_subnet_id: "{{ ec2_subnet_ids|random }}"
     region: "{{ ec2_region }}"
     instance_tags: "{{ ec2_tags }}"
     assign_public_ip: yes
     wait: true
     count: 1
     volumes: {{ volume }}
   register: ec2

 - debug: var=item
   with_items: ec2.instances

 - name: Add provisioned ec2 instances to in memory inventory
   add_host: name={{ item.public_ip }} >
             groups={{ environ }}_instances
             {{ ec2_tags }}
   with_items: ec2.instances

 - name: Wait for the instances to boot by checking the ssh port
   wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
   with_items: ec2.instances
